/**
 * SUNNY GURJAR — VIRAL REELS, FAST HIGHLIGHTS & WEDDING EDITS (2026)
 * Local Autoplay MP4 Videos & Direct Instagram Links
 */

const SUNNY_PROJECTS = {
  reels: [
    {
      id: "reel-highlight-vip",
      shortcode: "18087705284249666",
      videoSrc: "assets/videos/reel_08.mp4",
      instagramUrl: "https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDg3NzA1Mjg0MjQ5NjY2?story_media_id=3881450035560398636_29404321805&igsh=cjlsMzRoaDl5bWF2",
      title: "⚡ Fast Highlights & Viral Edits",
      client: "Sunny Gurjar Official Highlights",
      tool: "CapCut Pro & DaVinci",
      duration: "0:15",
      views: "4.8M",
      retention: "155% Replay Rate",
      category: "Featured Fast Highlights",
      description: "Rapid-fire montage featuring high-impact sound design, lightning-fast cuts, motion graphics, and high-energy pacing from Sunny's official Instagram Highlights.",
      tags: ["⚡ Fast Highlights", "Rapid Montages", "High Energy", "Story Highlights"],
      theme: "cyberpunk",
      isHighlight: true
    },
    {
      id: "reel-01",
      shortcode: "Da2rQqRvPw7",
      videoSrc: "assets/videos/reel_01.mp4",
      instagramUrl: "https://www.instagram.com/reel/Da2rQqRvPw7/",
      title: "Viral Reel #1 — Kinetic Impact",
      client: "Sunny Gurjar Creator Series",
      tool: "CapCut Pro",
      duration: "0:25",
      views: "1.8M",
      retention: "94% Avg Retention",
      category: "Viral Short-Form",
      description: "High-retention vertical short-form reel with velocity speed ramps, kinetic auto-captions, and precision audio beat synchronization.",
      tags: ["Velocity Curves", "Beat Sync", "9:16 Infinite Loop", "Motion Captions"],
      theme: "cyberpunk"
    },
    {
      id: "reel-02",
      shortcode: "DbGKZv8Bph_",
      videoSrc: "assets/videos/reel_02.mp4",
      instagramUrl: "https://www.instagram.com/reel/DbGKZv8Bph_/",
      title: "Viral Reel #2 — Cinematic Grade",
      client: "Sunny Gurjar Production",
      tool: "DaVinci Resolve",
      duration: "0:30",
      views: "1.2M",
      retention: "91% Avg Retention",
      category: "Cinematic Reel",
      description: "DaVinci Resolve color-graded short-form narrative with multi-track sound effects, dialogue clarity, and seamless pacing.",
      tags: ["Color Science", "Sound Design", "Pacing", "Visual Hook"],
      theme: "neon"
    },
    {
      id: "reel-03",
      shortcode: "DbKiZvezNAn",
      videoSrc: "assets/videos/reel_03.mp4",
      instagramUrl: "https://www.instagram.com/reel/DbKiZvezNAn/",
      title: "Viral Reel #3 — High-Energy Cut",
      client: "Creator Spotlight",
      tool: "CapCut Pro",
      duration: "0:22",
      views: "2.4M",
      retention: "115% Replay Rate",
      category: "Fast Paced Velocity",
      description: "Ultra dynamic match-cutting with speed curve ramps, visual glitch accents, and viral audio synchronization.",
      tags: ["Speed Ramps", "Match Cuts", "Glitch FX", "Viral Trend"],
      theme: "matrix"
    },
    {
      id: "reel-04",
      shortcode: "DXJAm3akcO1",
      videoSrc: "assets/videos/reel_04.mp4",
      instagramUrl: "https://www.instagram.com/reel/DXJAm3akcO1/",
      title: "Viral Reel #4 — Aesthetic Flow",
      client: "Brand Campaign",
      tool: "DaVinci Resolve",
      duration: "0:28",
      views: "950K",
      retention: "89% Avg Retention",
      category: "Aesthetic Reel",
      description: "Moody aesthetic reel with custom color grading, smooth push-in transitions, and ambient atmospheric sound design.",
      tags: ["Color Grade", "Smooth Transitions", "Atmospheric SFX", "Aesthetic"],
      theme: "glitch"
    },
    {
      id: "reel-05",
      shortcode: "DZxI_y-BGWo",
      videoSrc: "assets/videos/reel_05.mp4",
      instagramUrl: "https://www.instagram.com/reel/DZxI_y-BGWo/",
      title: "Viral Reel #5 — Motion & Subtitles",
      client: "Social Media Series",
      tool: "CapCut Pro",
      duration: "0:35",
      views: "1.4M",
      retention: "93% Avg Retention",
      category: "Talking Head / Dialogue",
      description: "Dialogue-focused vertical reel with highlighted word-by-word captions, dynamic B-roll popups, and zoom punch-ins.",
      tags: ["Word-by-Word Subtitles", "Zoom Punch-Ins", "B-Roll Popups", "Dialogue"],
      theme: "cyberpunk"
    },
    {
      id: "reel-06",
      shortcode: "DZNThUwTdjc",
      videoSrc: "assets/videos/reel_06.mp4",
      instagramUrl: "https://www.instagram.com/reel/DZNThUwTdjc/",
      title: "Viral Reel #6 — Seamless Loop",
      client: "Growth Edition",
      tool: "CapCut Pro",
      duration: "0:18",
      views: "3.1M",
      retention: "142% Replay Rate",
      category: "Infinite Looper",
      description: "Engineered for maximum algorithm replay value with a seamless hidden cut connecting the ending back to the first second.",
      tags: ["Seamless Loop", "Algorithm Retention", "Audio Hook", "CapCut Pro"],
      theme: "neon"
    },
    {
      id: "reel-07",
      shortcode: "DYZgPgdsE9c",
      videoSrc: "assets/videos/reel_07.mp4",
      instagramUrl: "https://www.instagram.com/reel/DYZgPgdsE9c/",
      title: "Viral Reel #7 — Master Reel",
      client: "Signature Edit",
      tool: "DaVinci Resolve",
      duration: "0:40",
      views: "2.1M",
      retention: "97% Avg Retention",
      category: "Signature Master",
      description: "Full-spectrum showcase combining cinema color grading, complex motion tracking, sound effects layering, and viral hook delivery.",
      tags: ["Cinema Grade", "Motion Tracking", "Layered SFX", "DaVinci Resolve"],
      theme: "matrix"
    },
    {
      id: "reel-08",
      shortcode: "DYBfRmjzWPx",
      videoSrc: "assets/videos/reel_08.mp4",
      instagramUrl: "https://www.instagram.com/reel/DYBfRmjzWPx/",
      title: "Viral Reel #8 — Dynamic Rhythm",
      client: "Creator Spotlight",
      tool: "CapCut Pro",
      duration: "0:24",
      views: "1.6M",
      retention: "95% Avg Retention",
      category: "Rhythm & Speed",
      description: "High-paced reel engineered around rhythmic audio cuts, rapid velocity shifts, and impactful bass drops.",
      tags: ["Rhythm Cuts", "Velocity Shifts", "Sound Sync", "CapCut Pro"],
      theme: "cyberpunk"
    },
    {
      id: "reel-09",
      shortcode: "DN-ssC_k47G",
      videoSrc: "assets/videos/reel_09.mp4",
      instagramUrl: "https://www.instagram.com/reel/DN-ssC_k47G/",
      title: "Viral Reel #9 — Visual Hook Master",
      client: "Brand Campaign",
      tool: "DaVinci Resolve",
      duration: "0:32",
      views: "2.8M",
      retention: "128% Replay Rate",
      category: "Visual Hook",
      description: "Immediate first-second visual hook design that stops the scroll, paired with rich cinema tones and fluid motion transitions.",
      tags: ["Hook Design", "Scroll Stopper", "Color Grade", "DaVinci Resolve"],
      theme: "neon"
    },
    {
      id: "reel-10",
      shortcode: "DXdaYg6kdNC",
      videoSrc: "assets/videos/reel_10.mp4",
      instagramUrl: "https://www.instagram.com/reel/DXdaYg6kdNC/",
      title: "Viral Reel #10 — Narrative Punch",
      client: "Series Production",
      tool: "CapCut Pro",
      duration: "0:29",
      views: "1.9M",
      retention: "92% Avg Retention",
      category: "Narrative Short",
      description: "Punchy short-form storytelling cut with kinetic typography overlays, B-roll timing, and dynamic sound effects.",
      tags: ["Kinetic Typography", "Sound Design", "Punchy Pacing", "CapCut Pro"],
      theme: "matrix"
    },
    {
      id: "reel-11",
      shortcode: "DawuEmFJMSG",
      videoSrc: "assets/videos/reel_11.mp4",
      instagramUrl: "https://www.instagram.com/reel/DawuEmFJMSG/",
      title: "Viral Reel #11 — High-Engagement Looper",
      client: "Viral Edition",
      tool: "DaVinci Resolve",
      duration: "0:20",
      views: "3.4M",
      retention: "148% Replay Rate",
      category: "Viral Looper",
      description: "Engineered for maximum shares and comments with precision sound design, color grading, and an addictive seamless loop.",
      tags: ["Seamless Loop", "Share Multiplier", "Color Science", "DaVinci Resolve"],
      theme: "glitch"
    }
  ],
  weddings: [
    {
      id: "wedding-01",
      shortcode: "DF6wkqeKe-t",
      videoSrc: "assets/videos/wedding_01.mp4",
      instagramUrl: "https://www.instagram.com/reel/DF6wkqeKe-t/",
      title: "Royal Wedding Film #1",
      tool: "DaVinci Resolve",
      duration: "0:45",
      retention: "DaVinci Color Science",
      category: "Royal Wedding Trailer",
      tags: ["Royal Wedding", "DaVinci Resolve", "Warm Gold Grade", "Sound Design"]
    },
    {
      id: "wedding-02",
      shortcode: "DRJ5Zzbku4U",
      videoSrc: "assets/videos/wedding_02.mp4",
      instagramUrl: "https://www.instagram.com/reel/DRJ5Zzbku4U/",
      title: "Cinematic Wedding Film #2",
      tool: "DaVinci Resolve",
      duration: "0:38",
      retention: "Cinematic Pacing",
      category: "Cinematic Wedding Teaser",
      tags: ["Cinematic Teaser", "Emotional Vows", "Color Separation", "Film Emulation"]
    },
    {
      id: "wedding-03",
      shortcode: "DSURvqAEim_",
      videoSrc: "assets/videos/wedding_03.mp4",
      instagramUrl: "https://www.instagram.com/reel/DSURvqAEim_/",
      title: "Haldi & Traditional Rituals #3",
      tool: "DaVinci & CapCut",
      duration: "0:32",
      retention: "Vibrant Haldi Colors",
      category: "Haldi & Rituals Film",
      tags: ["Haldi Highlights", "Vibrant Colors", "Slow Motion", "Acoustic SFX"]
    },
    {
      id: "wedding-04",
      shortcode: "DUEEyGVkj_P",
      videoSrc: "assets/videos/wedding_04.mp4",
      instagramUrl: "https://www.instagram.com/reel/DUEEyGVkj_P/",
      title: "Romantic Pre-Wedding Story #4",
      tool: "DaVinci Resolve",
      duration: "0:40",
      retention: "Romantic Flow",
      category: "Pre-Wedding Love Story",
      tags: ["Pre-Wedding", "Romantic Cut", "Dreamy Glow", "Pacing"]
    },
    {
      id: "wedding-05",
      shortcode: "DSUp6BOie-e",
      videoSrc: "assets/videos/wedding_05.mp4",
      instagramUrl: "https://www.instagram.com/reel/DSUp6BOie-e/",
      title: "Sangeet & Dance Celebration #5",
      tool: "CapCut Pro",
      duration: "0:30",
      retention: "Dance Beat Sync",
      category: "Sangeet Fast Highlights",
      tags: ["Sangeet Dance", "Beat Drop Sync", "Velocity Curves", "Celebration"]
    },
    {
      id: "wedding-06",
      shortcode: "DF2le3GyEje",
      videoSrc: "assets/videos/wedding_06.mp4",
      instagramUrl: "https://www.instagram.com/reel/DF2le3GyEje/",
      title: "Signature Wedding Master #6",
      tool: "DaVinci Resolve",
      duration: "0:42",
      retention: "Signature 4K Master",
      category: "Signature Wedding Trailer",
      tags: ["Signature Edit", "Color Grade", "Multi-Track SFX", "DaVinci Resolve"]
    },
    {
      id: "wedding-07",
      shortcode: "DbaxaezNOyk",
      videoSrc: "assets/videos/wedding_07.mp4",
      instagramUrl: "https://www.instagram.com/reel/DbaxaezNOyk/",
      title: "Royal Bride & Groom Cinematic Edit #7",
      tool: "DaVinci Resolve",
      duration: "0:36",
      retention: "Royal Golden Grade",
      category: "Royal Bridal Teaser",
      tags: ["Royal Portrait", "DaVinci Resolve", "Golden Tones", "Cinematic Cut"]
    },
    {
      id: "wedding-08",
      shortcode: "DZ48QsyNZ1a",
      videoSrc: "assets/videos/wedding_08.mp4",
      instagramUrl: "https://www.instagram.com/reel/DZ48QsyNZ1a/",
      title: "Vows & Celebration Masterpiece #8",
      tool: "DaVinci & CapCut",
      duration: "0:44",
      retention: "Emotional Vows & Flow",
      category: "Emotional Vows & Highlight",
      tags: ["Emotional Vows", "Audio Mixing", "Slow-Motion", "DaVinci Resolve"]
    }
  ]
};

if (typeof module !== 'undefined') {
  module.exports = SUNNY_PROJECTS;
}
